//// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
//#nullable disable
//using System;
//using System.Collections.Generic;

//namespace ChocoLuxAPI.Models;

//public partial class Order
//{
//    public int OrderId { get; set; }

//    public string UserId { get; set; }

//    public DateTime OrderDate { get; set; }

//    public int Status { get; set; }

//    public int? TotalPrice { get; set; }

//    public virtual ICollection<OrderDetail> tblOrderDetails { get; set; } = new List<OrderDetail>();
//}