//// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
//#nullable disable
//using System;
//using System.Collections.Generic;

//namespace ChocoLuxAPI.Models;

//public partial class OrderDetail
//{
//    public int OrderItemId { get; set; }

//    public int ProductId { get; set; }

//    public string ProductName { get; set; }

//    public int? Quantity { get; set; }

//    public int? product_price { get; set; }

//    public int? TotalPrice { get; set; }

//    public int OrderId { get; set; }

//    public virtual Order Order { get; set; }
//}