// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ChocoLuxAPI.Models;

public partial class Product
{
    public int product_id { get; set; }

    public string product_name { get; set; }

    public string product_description { get; set; }

    public int? product_price { get; set; }

    public string product_ImagePath { get; set; }

    public int CategoryId { get; set; }

    public virtual Category Category { get; set; }
}